//
// ProductsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class ProductsAPI: APIBase {
    /**
     Product Types
     
     - parameter latitude: (query) Latitude component of location. 
     - parameter longitude: (query) Longitude component of location. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func productsGet(latitude: Double, longitude: Double, completion: @escaping ((_ data: [Product]?,_ error: Error?) -> Void)) {
        productsGetWithRequestBuilder(latitude: latitude, longitude: longitude).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Product Types
     - GET /products
     - The Products endpoint returns information about the *Uber* products offered at a given location. The response includes the display name and other details about each product, and lists the products in the proper display order. 
     - examples: [{contentType=application/json, example=[ {
  "image" : "aeiou",
  "product_id" : "aeiou",
  "description" : "aeiou",
  "display_name" : "aeiou",
  "capacity" : "aeiou"
} ]}]
     
     - parameter latitude: (query) Latitude component of location. 
     - parameter longitude: (query) Longitude component of location. 

     - returns: RequestBuilder<[Product]> 
     */
    open class func productsGetWithRequestBuilder(latitude: Double, longitude: Double) -> RequestBuilder<[Product]> {
        let path = "/products"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [
            "latitude": latitude,
            "longitude": longitude
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Product]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
