//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class UserAPI: APIBase {
    /**
     User Activity
     
     - parameter offset: (query) Offset the list of returned results by this amount. Default is zero. (optional)
     - parameter limit: (query) Number of items to retrieve. Default is 5, maximum is 100. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func historyGet(offset: Int32? = nil, limit: Int32? = nil, completion: @escaping ((_ data: Activities?,_ error: Error?) -> Void)) {
        historyGetWithRequestBuilder(offset: offset, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     User Activity
     - GET /history
     - The User Activity endpoint returns data about a user's lifetime activity with Uber. The response will include pickup locations and times, dropoff locations and times, the distance of past requests, and information about which products were requested.<br><br>The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
     - examples: [{contentType=application/json, example={
  "offset" : 123,
  "limit" : 123,
  "count" : 123,
  "history" : [ {
    "uuid" : "aeiou"
  } ]
}}]
     
     - parameter offset: (query) Offset the list of returned results by this amount. Default is zero. (optional)
     - parameter limit: (query) Number of items to retrieve. Default is 5, maximum is 100. (optional)

     - returns: RequestBuilder<Activities> 
     */
    open class func historyGetWithRequestBuilder(offset: Int32? = nil, limit: Int32? = nil) -> RequestBuilder<Activities> {
        let path = "/history"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [
            "offset": offset?.encodeToJSON(),
            "limit": limit?.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Activities>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     User Profile
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func meGet(completion: @escaping ((_ data: Profile?,_ error: Error?) -> Void)) {
        meGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     User Profile
     - GET /me
     - The User Profile endpoint returns information about the Uber user that has authorized with the application.
     - examples: [{contentType=application/json, example={
  "last_name" : "aeiou",
  "promo_code" : "aeiou",
  "first_name" : "aeiou",
  "email" : "aeiou",
  "picture" : "aeiou"
}}]

     - returns: RequestBuilder<Profile> 
     */
    open class func meGetWithRequestBuilder() -> RequestBuilder<Profile> {
        let path = "/me"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Profile>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
